// ------------------------------------------------------------------------------------
// .NET Aspire AppHost
//
// This AppHost orchestrates the Postgres example end-to-end:
//   1. Spins up a PostgreSQL container (with a persistent data volume)
//   2. Adds pgAdmin so you can browse the database from your browser
//   3. Creates a database named "biele_ef_examples"
//   4. Launches the Bielu.Ef.Examples.Api.Postgres service and wires the
//      Postgres connection string into it via service discovery.
// ------------------------------------------------------------------------------------

var builder = DistributedApplication.CreateBuilder(args);

// Postgres server resource. The username/password are generated by Aspire and
// surfaced to the API via the "biele-ef-examples-db" connection string.
var postgres = builder.AddPostgres("postgres")
    .WithDataVolume()   // Persist data across AppHost runs
    .WithPgAdmin();     // Expose pgAdmin UI for inspection

// Logical database that lives on the postgres server. Aspire ensures the
// database is created on first launch.
var database = postgres.AddDatabase("biele-ef-examples-db");

// API service that consumes the Postgres database. The connection string
// referenced here matches the name configured by AddConnectionString
// (`builder.AddNpgsqlDbContext<...>("biele-ef-examples-db")`) inside the API.
builder.AddProject<Projects.Bielu_Ef_Examples_Api_Postgres>("api-postgres")
    .WithReference(database)
    .WaitFor(database);

// Second API service that consumes the same Postgres database. It demonstrates
// the bielu EF Core versioning library on Postgres — its ContentDbContext
// owns its own table set (Contents) and is independent from the multi-context
// example above, so they can happily coexist on the same logical database.
builder.AddProject<Projects.Bielu_Ef_Examples_Api_Postgres_Versioning>("api-postgres-versioning")
    .WithReference(database)
    .WaitFor(database);

builder.Build().Run();
